CREATE TABLE `gbp_scheduled_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`gbpAccountId` int NOT NULL,
	`topicType` enum('STANDARD','EVENT','OFFER') NOT NULL DEFAULT 'STANDARD',
	`summary` text NOT NULL,
	`mediaUrl` text,
	`callToActionType` enum('BOOK','ORDER','SHOP','LEARN_MORE','SIGN_UP','CALL'),
	`callToActionUrl` text,
	`eventTitle` varchar(255),
	`eventStartAt` timestamp,
	`eventEndAt` timestamp,
	`scheduledAt` timestamp NOT NULL,
	`status` enum('pending','published','failed','cancelled') NOT NULL DEFAULT 'pending',
	`gbpPostId` int,
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `gbp_scheduled_posts_id` PRIMARY KEY(`id`)
);
